### Get Session
http://localhost:8080/api/v1/chatbot/asdasdasad
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJva2MwMjAyIiwiZXhwIjoxNzYwNzg2ODQxLCJrZXkiOiJ0bVVHOEw0eFA0XzJJT2Y4WDNNTzZBIiwicm9sZSI6IuydvOuwmCDsgqzsmqnsnpAifQ.Ayg0H4TVfm0qKEjneUgnXns37Fbl2rZoN62zDy-ABKW8khcsqjGdnzTi88GIjZaLm6WfDEQ8vpyvV_psm9PDrw

### Create ChatBot
POST http://localhost:8080/api/v1/chatbot/room?title=demo
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJva2MwMjAyIiwiZXhwIjoxNzYwOTY4OTIwLCJrZXkiOiJqOGF0R0ZaRjNjWlBRbnhRVkE3QVBRIiwicm9sZSI6IuydvOuwmCDsgqzsmqnsnpAifQ.pDKLVh6Uo_TNAe8gS-SgEMA0xrxAxvb2RWWm1FtwDTEhfQwjwjizugf5B3ywelzD8IPJgBPs7H5ei3DXQNQ5Hg

### Get Room
GET http://localhost:8080/api/v1/chatbot/rooms
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJva2MwMjAyIiwiZXhwIjoxNzYwOTY4OTIwLCJrZXkiOiJqOGF0R0ZaRjNjWlBRbnhRVkE3QVBRIiwicm9sZSI6IuydvOuwmCDsgqzsmqnsnpAifQ.pDKLVh6Uo_TNAe8gS-SgEMA0xrxAxvb2RWWm1FtwDTEhfQwjwjizugf5B3ywelzD8IPJgBPs7H5ei3DXQNQ5Hg

