### Get Session
http://localhost:8080/api/v1/chatbot/asdasdasad
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJva2MwMjAyNzgiLCJleHAiOjE3NjE3MzQxMTYsImtleSI6IjZQdWw4TmQ4TW52aEdxbzlFS3phVlEiLCJyb2xlIjoi7J2867CYIOyCrOyaqeyekCJ9.lyVqPQiMgo-5uVXdBpbt2P_5AoiAd-bw82SY1Gk9unOcdxuayxVc0qK7KlnBAfn_aV1bs42HO-S_F0XL1zh7Rg

### Create ChatBot
POST http://localhost:8080/api/v1/chatbot/room?title=demo
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJva2MwMjAyNzgiLCJleHAiOjE3NjE3MzQxMTYsImtleSI6IjZQdWw4TmQ4TW52aEdxbzlFS3phVlEiLCJyb2xlIjoi7J2867CYIOyCrOyaqeyekCJ9.lyVqPQiMgo-5uVXdBpbt2P_5AoiAd-bw82SY1Gk9unOcdxuayxVc0qK7KlnBAfn_aV1bs42HO-S_F0XL1zh7Rg
Idempotency-Key: Idempotency

### Get Room
GET http://localhost:8080/api/v1/chatbot/rooms
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJva2MwMjAyNzgiLCJleHAiOjE3NjE3MzQxMTYsImtleSI6IjZQdWw4TmQ4TW52aEdxbzlFS3phVlEiLCJyb2xlIjoi7J2867CYIOyCrOyaqeyekCJ9.lyVqPQiMgo-5uVXdBpbt2P_5AoiAd-bw82SY1Gk9unOcdxuayxVc0qK7KlnBAfn_aV1bs42HO-S_F0XL1zh7Rg

