### Token 테스트 요청
GET http://localhost:8080/api/v1/places
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJva2MwMjAyIiwiZXhwIjoxNzU3NTEwOTQxLCJrZXkiOiJNV1pwMkZKdVNUM3pfc2J4bXluU2xnIiwicm9sZSI6IuydvOuwmCDsgqzsmqnsnpAifQ.HQ8hZAkYSF7fVgYUPcxpiL8V1_RH72jYXXsFZG_cHuOpmAPrJ0Yh8nRroofn0TphpIe3IqUS-CUXzlPAaAjWCA
Accept: application/json
