spring:
  application:
    name: Vett-Place-Service

  config:
    activate:
      on-profile: local
    import: optional:file:.env[.properties]

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      observation-enabled: true
    consumer:
      enable-auto-commit: false
    template:
      observation-enabled: true


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  datasource:
    url: ${RDB_URL}
    username: ${RDB_USERNAME}
    password: ${RDB_PASSWORD}

  data:
    redis:
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      host: ${REDIS_HOST}
      repositories:
        enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVICE_URL}

logstash:
  host: ${LOGSTASH_HOST}

server:
  port: 8082
  servlet:
    session:
      timeout: 60m
      persistent: true

app:
  secret:
    passport: ${APP_PASSPORT_SECRET}
  kakao:
    api:
      key: ${KAKAO_API_KEY}
    address-to-coordinate:
      host: ${KAKAO_ADDRESS_TO_COORDINATE_HOST}
      path: ${KAKAO_ADDRESS_TO_COORDINATE_PATH}
    route:
      host: ${KAKAO_ROUTE_HOST}
      path: ${KAKAO_ROUTE_PATH}
