spring:
  application:
    name: Vett-Place-Service

  config:
    activate:
      on-profile: local
    import: optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  datasource:
    url: ${RDB_URL}
    username: ${RDB_USERNAME}
    password: ${RDB_PASSWORD}

  data:
    redis:
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      host: ${REDIS_HOST}
      repositories:
        enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}

server:
  port: 8082
  servlet:
    session:
      timeout: 60m
      persistent: true

app:
  secret:
    passport: ${APP_PASSPORT_SECRET}
  kakao:
    api:
      key: ${KAKAO_API_KEY}
    address-to-coordinate:
      host: ${KAKAO_ADDRESS_TO_COORDINATE_HOST}
      path: ${KAKAO_ADDRESS_TO_COORDINATE_PATH}
    route:
      host: ${KAKAO_ROUTE_HOST}
      path: ${KAKAO_ROUTE_PATH}
