### 회원가입
### PK - aAPzwpKf-0mFtlfbU1wCWA
POST http://localhost:8081/api/v1/auth/signup
Content-Type: application/json
Idempotency-Key: Idempotencyasdsad

{
  "name" : "오규찬",
  "userId" : "test1234",
  "password" : "!test1234",
  "email" : "okc0202@naver.com"
}

### 로그인
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json
Idempotency-Key: asdasdasdas

{
  "userId" : "okc0202",
  "password" : "!159753okcA"
}

### 아이디 찾기
GET http://localhost:8081/api/v1/auth/find-id?name=오규찬&email=okc0202@naver.com

### 이건 DB 호출 없음
### GET USER
GET http://localhost:8081/api/v1/user/me
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJva2MwMjAyNzgiLCJleHAiOjI2MjQyNzMzNTcsImtleSI6InJsSHBhcFhJWDZ1T2hVTGpiVWdoSlEiLCJyb2xlIjoi7J2867CYIOyCrOyaqeyekCJ9.MmqjiWbWTcdfBfTsf5W5MAs456DuUBSjjolSdj58mYx2tQFqJD9T60PPCM0U3cceviF_8WdYLQULZiga_8zD3g

### DELETE USER
DELETE http://localhost:8080/api/v1/user/me
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJva2MwMjAyNzgiLCJleHAiOjI2MjQyNzMzNTcsImtleSI6InJsSHBhcFhJWDZ1T2hVTGpiVWdoSlEiLCJyb2xlIjoi7J2867CYIOyCrOyaqeyekCJ9.MmqjiWbWTcdfBfTsf5W5MAs456DuUBSjjolSdj58mYx2tQFqJD9T60PPCM0U3cceviF_8WdYLQULZiga_8zD3g

### PATCH USER
PATCH http://localhost:8081/api/v1/user/me
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJva2MwMjAyNzgiLCJleHAiOjI2MjQyNzMzNTcsImtleSI6InJsSHBhcFhJWDZ1T2hVTGpiVWdoSlEiLCJyb2xlIjoi7J2867CYIOyCrOyaqeyekCJ9.MmqjiWbWTcdfBfTsf5W5MAs456DuUBSjjolSdj58mYx2tQFqJD9T60PPCM0U3cceviF_8WdYLQULZiga_8zD3g
Content-Type: application/json

{
  "name" : "찬2",
  "email" : "okc0202@naver.com"
}

### GET PASSPORT
GET http://localhost:8081/api/v1/user/passport
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJva2MwMjAyNzgiLCJleHAiOjI2MjQyNzMzNTcsImtleSI6InJsSHBhcFhJWDZ1T2hVTGpiVWdoSlEiLCJyb2xlIjoi7J2867CYIOyCrOyaqeyekCJ9.MmqjiWbWTcdfBfTsf5W5MAs456DuUBSjjolSdj58mYx2tQFqJD9T60PPCM0U3cceviF_8WdYLQULZiga_8zD3g

### DELETE Member
DELETE http://localhost:8081/api/v1/user/me
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJva2MwMjAyNzgiLCJleHAiOjI2MjQyNzMzNTcsImtleSI6InJsSHBhcFhJWDZ1T2hVTGpiVWdoSlEiLCJyb2xlIjoi7J2867CYIOyCrOyaqeyekCJ9.MmqjiWbWTcdfBfTsf5W5MAs456DuUBSjjolSdj58mYx2tQFqJD9T60PPCM0U3cceviF_8WdYLQULZiga_8zD3g




