spring:
  application:
    name: VettEurekaService

  config:
    activate:
      on-profile: local
    import: optional:file:.env[.properties]

server:
  port: 8761

logstash:
  host: ${LOGSTASH_HOST}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
